### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by MariuszPodlasie** [ZhooL/TSX_EnhancedVehicle#1]
Great mod. Respect for you for it. However, I have a proposal to change the size of the font to a larger (more readable) and to change the position of one window, because after changing the size of the font, it is not fully visible.
I pictured this on the attached screen.
I am sorry if my request contains language errors, I do not write in English best.
![bez tytulu2](https://user-images.githubusercontent.com/46301601/50575308-0f887980-0dfd-11e9-9e2c-fa51293d1add.png)

**Comment by ZhooL** [comment]
Thanks for your feedback. I never thought anyone would modify the fontSize value ;-) Let me think about re-arranging some elements to reduce the bottom info block to one text line only.

**Comment by dlehman83** [comment]
+1 for this, I too modified the font size and now cannot see the weight.  The default font was just too small for my monitor.  Perhaps make it an option to change font size in game.  
Thanks,

**Comment by MariuszPodlasie** [comment]
The version v1.4.0.0 is really great. Introducing an XML file was what it lacked. I am impressed by your work. Finally, it looks like it looks like on the attached screen. I have modified only the font size for your needs to 0.0145 (do not hold it against me). The default size was too small on the big screen.
Best wishes and Happy New Year  ;)
![fsscreen_2019_01_03_09_19_59](https://user-images.githubusercontent.com/46301601/50629103-875cbe00-0f3b-11e9-8eb8-6d2844b05c19.png)

**Comment by ZhooL** [comment]
You're welcome :-)
