### ISSUE TITLE
Reversing lights not working

### ISSUE THREAD

**Issue by knuuud** [ZhooL/TSX_EnhancedVehicle#11]
Just as the title said, the reversing lights does not activate until you change forward again, and than only for a brief second.

The rest seems very good on the shuttle

**Comment by spocane** [comment]
Can Confirm this as well. Same thing happens with the reversing alarm.

**Comment by ZhooL** [comment]
Well this is kind of a point of view. In shuttle you're not driving backwards - you're driving forwards in the opposite direction and so no reverse driving lights are required. That's at least what the engine does. The vehicle moves forwards and only the reverser unit in the gearbox changes the actual moving direction.
But lemme check what I can do about the lights...

**Comment by ZhooL** [comment]
a bit better in 1.5.1.1 but I can't get the beep beep sound working correctly
