### ISSUE TITLE
Jenz BA 725 D

### ISSUE THREAD

**Issue by knuuud** [ZhooL/TSX_EnhancedVehicle#12]
Found a issue with the Jenz BA 725 D. When a tractor is connected to it the shuttle control and other functions on tractors are not working. Once disconnected than the controlls works perfect again. Might be because it is driveable?

No log errors, so to reproduse you will have to test yourself.

My used config:
Fendt Favorit 515C
Jenz BA 725 D

Issue appears on other tractors with the Jenz BA 725 D as well

**Comment by ZhooL** [comment]
fixed in 1.5.1.1
