### ISSUE TITLE
Some trucks only spin

### ISSUE THREAD

**Issue by knuuud** [ZhooL/TSX_EnhancedVehicle#13]
when using shuttle some of the trucks ingame spin and is not responding correct. Not tested all vehicles but trucks are affected

**Comment by ZhooL** [comment]
I can't reproduce. Tested with some trucks now and they behave normal. With and without attached trailers or whatever.

**Comment by knuuud** [comment]
Hmm I did another test. In SP it works fine, while in MP you get the spin when changing. I will see if I can do a screencap for you. The server log and my local log has no warnings or errors. Can it be some kind of sync issue, only it does not show on tractors as they have grip setup another way?

**Comment by knuuud** [comment]
Can be closed. This has been fixed in last update it appears. 👍
