### ISSUE TITLE
Shuttlefunktion

### ISSUE THREAD

**Issue by hoefti10** [ZhooL/TSX_EnhancedVehicle#15]
Moin, zuerst möchte ich dir für den tollen Mod danken. 
Wirklich sehr hilfreich und gut gemacht. Allerdings ist mir in der neuen Version aufgefallen das scheinbar die Shuttlefunktion von Keyboardsteer geforced (überschrieben)wird was ich sehr schade finde.
Ich habe bisland die Shuttlefunktion von Keyboardsteer genutzt das mir die Kameradrehung gut gefallen hat. Jetzt steck ich in der Klemme.
Kann man da evtl. irgendwie ein Mittelweg finden die funktionen von beiden Mods nutzen zu können wie man will, wie in der alten Version beispielsweise?
MfG

**Comment by sootysax** [comment]
since it looks like Mogli has quit modding for FS (again), i think i will replace keyboard steer with this mod entirely

**Comment by hoefti10** [comment]
He uplouded the last time for 8days ago his keyboardsteer? Why he should stop modding?

**Comment by fdanapfel** [comment]
@hoefti10: looks like this mod is actually the reason why mogli has decided to quit working on his mods, see https://github.com/Mogli12/KeyboardSteer/issues/106#issuecomment-452596956

I would also appreciate it if the shuttle function in this mod could be disabled via the config file, so that people can decide if the want to use the one from Keyboardsteer or the one from the mod.

**Comment by ZhooL** [comment]
Nun es ist jedem selbst überlassen welche Mods er nutzen möchte. Ich schreibe meinen Mod so, daß er mir den Spielspaß erhöht mit den Dingen, die mir gefallen. Gerne teile ich meine Arbeit mit der Community, aber "so wie der Mod ist". Mir ist keyboardSteer natürlich bekannt, aber ich nutze es nicht. In meinen technischen Möglichkeiten versuche ich dennoch eine maximale Kompatibilität mit dem anderen Mod hinzubekommen. Dabei nehme ich es mir aber heraus meine Version vom Shuttle zu bevorzugen.

**Comment by ZhooL** [comment]
Mit 1.5.1.2 beende ich jetzt auch die Integrationsarbeiten mit keyboardSteer. Die Zurückschau-Kamera funktioniert wieder - das muß reichen.
