### ISSUE TITLE
Shuttle not working with keyboardSteer

### ISSUE THREAD

**Issue by Harag9** [ZhooL/TSX_EnhancedVehicle#16]
I use the KeyboardSteer mod and been using the space bar for shuttle.

I've just downloaded your latest version as of now (1.5.1.2) and it disables the shuttle to use your version.  Even though the UI works fine and it shows the shuttle change from forward/reverse, when it's in reverse it still goes forward. I've tried it on several tractors now and all act the same.

BTW, Love the new layout, much better looking!

**Comment by ZhooL** [comment]
Download again now and try out

**Comment by Harag9** [comment]
Excellent, I'll download this and try again

EDIT - Just noticed you updated it again 30 mins ago, so downloaded that version just now before launching game - Quick test in game and the shuttle seems to work now with the keyboardSteer mod - Many thanks for sorting this so quickly!
