### ISSUE TITLE
Bei mir funktioniert das Skript nicht :-((

### ISSUE THREAD

**Issue by Amadeo01** [ZhooL/TSX_EnhancedVehicle#17]
Irgendwie funktioniert die Mod bei mir überhaupt nicht. ---> Traurig. :-((

Ich spiele mit dem Gamepad und habe die Funktionen "Vor- u. Rückwärtsgang" auf die rechte Schultertaste gelegt wie beim keyboardSteer (möchte ich nicht mehr nutzen) zuvor auch. Das Umschalten auf Taste Y.
Der Traktor fährt nur rückwärts und vorwärts nur mit der Einstellung des Tempomaten. Die grüne Markierung springt von vorwärts immer gleich auf Rückwärts; beim Betätigen der Schultertaste.

Die anderen Einstellungen (Differenziale, Allrad) liegen auf der Tastatur und funktionieren einwandfrei.

Was mache ich grundsätzlich falsch bei der Tastenbelegung? ... ZhooL, gib mir bitte einen Rat.

**Comment by ZhooL** [comment]
Ich kann deine Gamepad Belegung noch nicht ganz nachvollziehen. Schick mir die mal genauer für die folgenden Dinge:
![image](https://user-images.githubusercontent.com/11815468/51071773-cb944080-1656-11e9-90a3-cbef2227cca6.png)

**Comment by Amadeo01** [comment]
Ich habe diese Einstellungen vorgenommen.
![gamepad-einstellungen](https://user-images.githubusercontent.com/29040448/51072519-4adb4180-1662-11e9-8879-7c6c0b15888d.jpg)

**Comment by Amadeo01** [comment]
Sorry, ich hatte den falschen Button angeklickt und die Fragestellung geschlossen!

**Comment by Amadeo01** [comment]
Jetzt nach dem Neustart funktioniert nur noch der Tempomat-Vorwärtsgang und trotz Grün-Fahrtrichtungsmarker auf >Rückwärts< funktioniert dieser Gang nicht mehr.

**Comment by ZhooL** [comment]
Ah ich glaube Du hast da was falsch verstanden. Es geht nicht "beides". Entweder Du schaltest zwischen vorwärts/rückwärts mit einer Taste (bei Dir Y) um, ODER du aktivierst direkt vorwärts oder direkt rückwärts mit zwei anderen Tasten. Lösche die Gamepad Belegung für "EV: Fahrrichtung vorwärts" und "EV: Fahrrichtung rückwärts"
Und Wendeschaltung an/aus solltest Du auch nicht auf "LT" legen - dann schaltest Du immer an oder aus, wenn Du das Fahrzeug bremsen willst.

**Comment by Amadeo01** [comment]
Hab' s gerade nach deiner Anleitung ausprobiert und ... es funktioniert bestens! Ich danke dir sehr. :-))
Extrem supertolle Skript- Mod für den bislang doch irgendwie so realitätsfernen LS19.
