### ISSUE TITLE
issue with KBS

### ISSUE THREAD

**Issue by Bigmack73** [ZhooL/TSX_EnhancedVehicle#18]
This issue I found while using the cotton havester. I use the keyboard steer mod. When I snap to direction. Then go into reverse, it will start going in circles. Basically it does not go straight back. I hope I explained that ok. And I see that it disabled the shuttle in KBS. The "F" is gone.

**Comment by ZhooL** [comment]
Then I'm sorry, but I can't and won't do anything about it. Either use KBS or use my mod (or use both but don't snap backwards). If my Mod is active it will disable kbs shuttle automatically - that's why the "F" is gone.
