### ISSUE TITLE
Front/Rear Hydraulic up/down is not working with some implements

### ISSUE THREAD

**Issue by spocane** [ZhooL/TSX_EnhancedVehicle#19]
The New "Front/Rear Hydraulic up/down" is not working with some implements, from my testing it will turn on/off but will not lower down the following types of equipment:

Balers, Seeders(on/off,up/down does not work with the air cart seeders), Forage Wagons, Rear Mowers(works fine with the NewHolland Disc Bine), and the pull behind Potato and Sugar beet harvesters --Possibly more haven't tested everything.

It seems to have no issues with the on/off function (exception with the Air Seeders)

Thank you again for writing this excellent mod! I was going to suggest this feature as well.

**Comment by ZhooL** [comment]
Well I think it might be correct so. The mod lowers/raises the hydraulics of the main vehicle. It does not lower/raise anything "inside" the attached machinery. But let me debug a bit into it.

**Comment by ZhooL** [comment]
Download the current version 1.6.0.1 and try again please

**Comment by spocane** [comment]
All the machines I listed are now functioning, at least how i want them to. Thanks for the Fix!
