### ISSUE TITLE
Possibility to change / turn on-off some hud positions?

### ISSUE THREAD

**Issue by xCrazyDogx** [ZhooL/TSX_EnhancedVehicle#2]
Hello,

I love the mod, it gives info that default giants does not and therefor I like this mod. Mainly the damage on attached tools is very good and pleasant.

I use keyboardsteer mod for the snap option (steerlock) and that one has worldglobalposition plus if activated the snapangle on the  bottom right above the gauges. 
So basically this mod and keyboardsteer overlap each other making some info from this mod more diffcult to read.

2 images to show what I  mean by that :

![fsscreen_2019_01_02_10_48_28](https://user-images.githubusercontent.com/22746021/50587023-726d2580-0e7c-11e9-8675-dc81a34fdd63.png)

![fsscreen_2019_01_02_10_48_30](https://user-images.githubusercontent.com/22746021/50587025-7731d980-0e7c-11e9-9022-62e01a4f8c0f.png)

As you can see it makes some other stuff slighty more difficult to see.
Also the VehicleFruitHud is bottom right with it's tractor symbol instead of top left default giants, if you look closely. 

My question is if it could be an idea to have people move positions of huds or to have choice what they wanna have on from this extended mod? So it does not overlap with other mod(s) and keeps everything readable?

Would not like the idea that i have to choose one or the other mod :(

Keep up the great work.

**Comment by ZhooL** [comment]
Thanks for the feedback. The keyboardSteer overlap is resolved with version 1.4.0.0 (press "KeyPad /" to reset positions).
Regarding the tractor symbol - I never noticed it can be moved down there. Right now I will leave my output there. Maybe some day I have an idea where to put it :-)

**Comment by xCrazyDogx** [comment]
wow thank you very much, the tractor symbol : not a big issue ;) Again thank you ZhooL also for taking it so well.

Happy New Year

**Comment by ZhooL** [comment]
You can change positions of the HUD elements in the modsSettings\TSX_EnhancedVehicle\TSX_EnhancedVehicle.xml also.
