### ISSUE TITLE
Shuttle+Kamarablick

### ISSUE THREAD

**Issue by hoefti10** [ZhooL/TSX_EnhancedVehicle#20]
Moin,
Die Kamera dreht sich auch im Vorwärtsgang nach hinten wenn die Maschine zum stehen kommt, der Rückwärtsgang geht dabei auch kurzzeitig rein.
Die Kamera dreht sich scheinbar die ganze Zeit. Sprich wenn ich den Rückwärtsgang drin habe auf beschleunigen drückte, blicke ich nach vorne. Lasse ich Beschleunigen los dreht sich die Blickrichtung nach hinten.

Edit:
Ich bin ein voll Noob wenn es ums programmieren geht. hab jetzt die Codezeile die fürs Überschreiben von Keyboardsteer zuständig ist ausgeklammert, die Inputbinding von EV gelöscht und bekomme keine Fehler obwohl ich beide Mods nutze (Shuttle von Keyboardsteer und Parkbremse EV) Muss nur mal gucken wie ich die Ganganzeige von dir wieder aktiviert bekomme die finde ich schöner als die von Mogli :-)
👍

**Comment by ZhooL** [comment]
"der Rückwärtsgang geht dabei auch kurzzeitig rein."
Das klingt komisch, denn der kann bei mir nur reingehen, wenn entsprechende Taste gedrückt wird. Die Kamerablickrichtung ist stumpf an die Geschwindigkeit gekoppelt. größer 0 nach vorne schauen, kleiner 0 nach hinten schauen. Unabhängig von gewählten Gängen o.ä.

**Comment by hoefti10** [comment]
Hi, zu meinem beschämen ist das "Problem" jetzt weg. Ich habe es jetzt mit der neusten Version getestet , ich hatte die Version davor nicht mehr im Original nur noch die, die ich bearbeitet habe. Damit wollte ich allerding kein Video machen.
nur noch das " der Rückwärtsgang geht dabei kurzzeitig rein." ist noch sichtbar was aber kein wirklich Problem für mich darstellt.
Sorry das ich deine Zeit geraubt habe.
Nur nochmal kurz ein Video damit du siehst was ich meine. das aber wirklich kein Problem in dem Sinne.
https://youtu.be/gfDY8m03S48

Nichtsdestotrotz  toller Mod :-) 👍
