### ISSUE TITLE
Conflict with keyboardSteer "Look Backwards"

### ISSUE THREAD

**Issue by sootysax** [ZhooL/TSX_EnhancedVehicle#21]
So the new update no longer automatically turns off the "Look Backwards" option in KeyboardSteer, but when enabled, any time you step on the brake pedal, the camera switches to Look Backwards.  The camera does not Look Backwards when shifting driving direction with EV.

**Comment by ZhooL** [comment]
I made a minor change to the camera stuff, but this can't resolve your cam-back-on-brake effect. I can't reproduce that and from the code point of view it is even impossible to get that effect. Cam can only switch to back if the vehicle is actually moving backwards.
