### ISSUE TITLE
Last update broke shuttle on the servers.

### ISSUE THREAD

**Issue by knuuud** [ZhooL/TSX_EnhancedVehicle#22]
The last update broke sync of the mod to server. when playing on server almost everything is reversed and some things are not working. No log entries, only mod loaded is this.

**Comment by ZhooL** [comment]
will check today evening

**Comment by ZhooL** [comment]
I can't reproduce :-( singleplayer, multiplayer as host and as client, multiplayer client on dedi server... works all fine for me.

**Comment by knuuud** [comment]
Hmm 🤔 will try to "reset" config files and than try again. Not sure why it does this, but it is strange that it works fine in SP and than when in MP it flips the controls. If I get same error I will do a screen cap if I can get the input recording working. (haven't used that feature before, but might make it easier for you to see whats going on.)

**Comment by ZhooL** [comment]
Found it. New version of keyboardSteer. 1.6.0.2 adapts.
