### ISSUE TITLE
Farmer animations when backing up

### ISSUE THREAD

**Issue by knuuud** [ZhooL/TSX_EnhancedVehicle#23]
When using shuttle the farmer animations for reverse is not working correct. Shift leaver ismoving correctly, so its only the farmer. When backing up the farmer is pressing the brake pedal instead of trottle.

**Comment by ZhooL** [comment]
Well I won't fix that :-)

**Comment by knuuud** [comment]
It was working on earlier versions, but if thats the attitude I guess I will have to use keyboardsteer as he has allready fixed that issue. ;)

**Comment by ZhooL** [comment]
go for it :-)
