### ISSUE TITLE
Feature question

### ISSUE THREAD

**Issue by 206airmail** [ZhooL/TSX_EnhancedVehicle#24]
Is it possible to make the vehicles to where they roll if they are on a hill without the parking brake on?
Thank you so much for this mod! I used drive control all the time in 17, and it's nice to have something to replace it with!

**Comment by Harag9** [comment]
That would be a great enhancement, however i'm using the Keyboard steer and recently the parking break has vanished as KBS  has it's own shuttle functions now.

**Comment by ZhooL** [comment]
I'm no longer working on this mod. Sorry - no new features.
