### ISSUE TITLE
Kompatibilität mit KeyboardSteer

### ISSUE THREAD

**Issue by Mogli12** [ZhooL/TSX_EnhancedVehicle#25]
Hallo,

Hier mein Vorschlag. Ich habe diese Issue und eins in KeyboardSteer angelegt. https://github.com/Mogli12/KeyboardSteer/issues/118

Hier können wir die notwendigen Änderungen und die abgestimmten Versionsnummer austauschen. Mein erster Schwung von Anpassungen ist in https://github.com/Mogli12/KeyboardSteer/commit/05b7d5d8f73234e3a2a280943f8814945cde7dec.

Gruß, Stefan

**Comment by Mogli12** [comment]
Hallo,

ich überlege gerade, KeyboardSteer in 2 Mods zu zerschlagen. Eventuell reaktiviere ich dazu dann doch noch GearboxAddon, aber mit stark eingeschränkter Funktionalität. Shuttle Control wäre dann auch im anderen Mod. Wie wollen wir uns da synchronisieren?

Gruß,
Stefan

**Comment by ZhooL** [comment]
Hi,

gerne. Ich würde meinerseits weiterhin auf Shuttle Control verzichten, wenn eins von Dir erkannt wird (es sei denn der User schaltet es aktiv bei dir aus und bei mir an). Ich nehme mal an, die Shuttle-Funktionalität steckt/bleibt bei Dir in FS19_VehicleControlAddon? Ich halte dann Ausschau nach Funktionen bei Dir, woran ich den Shuttle-Status erkennen kann. Wenn Du auch Diffs und Hydraulik bei Dir machen möchtest - auch da finden wir einen Weg.

Gruß
Mario

**Comment by Mogli12** [comment]
Halo Mario,

ich habe die neue Methode self:vcaExternalGetShuttleCtrl() angelegt. Du brauchst also nicht nachschauen, ob der Mod geladen ist, sondern nur
```lua
    local vcaShuttleCtrl = false 
    if type( self.vcaExternalGetShuttleCtrl ) == "function" then 
      vcaShuttleCtrl = self:vcaExternalGetShuttleCtrl()
   end
```
Ich habe auch nochmal alle Funktionen unter dem alten Name (z.B. ksmExternalSetShuttleCtrl) bei self eingefügt.

Gruß, Stefan

**Comment by sootysax** [comment]
so whats the future of EV now that Mogli has 'quit modding for FS', again (it must be the 20th time).  Are you going to re-incorporate the shuttle control back into EV?

**Comment by Mogli12** [comment]
Hallo Mario,

Ich denke, dass wir das jetzt schließen können. 

Viele Grüße, 
Stefan

**Comment by ZhooL** [comment]
agreed :-)
