### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by mngrazy** [ZhooL/TSX_EnhancedVehicle#29]
servus ZhooL

frage zwecks config file

wäre es möglich die Text Colors zu ändern per config ?
und eventuell txtBold true/false

für mich persönlich zielt die einstellung auf die RPM und Temp anzeige , die beiden würd ich gern per config ändern und nicht immer in der lua rumfummeln ;)

grüsse grazy

**Comment by ZhooL** [comment]
I'm no longer working on this mod. Sorry - no new features.
