### ISSUE TITLE
dedi warning log

### ISSUE THREAD

**Issue by ZhooL** [ZhooL/TSX_EnhancedVehicle#31]
Load mod: TSX_EnhancedVehicle (Version: 1.6.3.0) (Hash: 00b12b8dd93feb339ffa62f525982629) Warning: Duplicate l10n entry 'EV_KS_warning5' in 'D:/home/sid_599734/farmingSim_2019/profile/mods/TSX_EnhancedVehicle/modDesc_l10n_en.xml'. Ignoring this defintion.

**Comment by ZhooL** [comment]
fixed in 1.6.3.1

**Comment by fdanapfel** [comment]
Where can version 1.6.3.1 be found? Because the current version available in the GitHub repo still produces this warning.
