### ISSUE TITLE
Hud clash with work rpm

### ISSUE THREAD

**Issue by Eloff7** [ZhooL/TSX_EnhancedVehicle#33]
Hud clashes with work rpm hid position. Is it possible to write something in so that it switches the work rpm hud of?

**Comment by xCrazyDogx** [comment]
Go to : 
My Documents\My Games\FarmingSimulator2019\modsSettings\TSX_EnhancedVehicle
Open up with notepad or notepad++ or similar
TSX_EnhancedVehicle_v1.xml

Look for the line starting with 
<rpm enabled="true"

set it to 
<rpm enabled="false" 

Do not remove anything behind it, only set true to false. 
Save it and rpm is gone.
it will not show ingame unless you press KeyPad * to reload XML config from disk to show modifications immediately without restarting the complete game.

Other option is to adjust the position where it is showing by going to
<rpm enabled="true"
and look for this part which determines its position on screen
posX="0.940283" posY="0.081287"

You can play with it, but turning it off is easiest if you are not sure what you are doing or if you do not need the rpm hud.
ANy changes you make will not show up ingame until you press KeyPad * to reload XML config from disk to show modifications immediately without restarting the complete game.

Worst case if it doesnt do the changes is that you have to restart your game if Keypad * doesnt respond.

That should help you to have the rpm off your screen.

**Comment by ZhooL** [comment]
thanks for helping out :-)

**Comment by Eloff7** [comment]
Thank you for your reply. any chance that you would add the  work rpm function into the TSX mod at some stage, then can get rid of work rpm mod
