### ISSUE TITLE
Shuttle Control?

### ISSUE THREAD

**Issue by XGrimHarlequinX** [ZhooL/TSX_EnhancedVehicle#45]
I may be missing a setting, but shuttle control doesn't seem to be working.  Neither my steering wheel nor my space bar seems to have any effect on changing drive direction.  I can turn shuttle control off (which disables all movement), but when turned on, nothing.  All other functions seem to work fine.  Is there a setting I need to toggle to enable drive direction?

**Comment by KITT3000** [comment]
@XGrimHarlequinX In some types of vehicles you need to use separate buttons for driving back and forth, this option does not work with one button I do not know why, but I had a problem with it in the Fendt Ideal 9T and only after I assigned the keys to separate directions I could change this direction driving.

**Comment by XGrimHarlequinX** [comment]
@KITT3000 Thanks, I'll fiddle with it to see if I can get it working.  Left wheel paddle, reverse; right wheel paddle, forward might work then.  I'll let you know.

**Comment by phwoelfel** [comment]
> I can turn shuttle control off (which disables all movement)

You probably turned it on and what disables the movement is the parking brake ;-)
The first time you activate it the parking brake is active (there is a red dot in the center of the two arrows). There is a seperate keybinding for the parking brake.

**Comment by XGrimHarlequinX** [comment]
@phwoelfel That was it!  Funny how something so simple can cause such a headache.
