### ISSUE TITLE
Ad Blue addon from Modhub

### ISSUE THREAD

**Issue by HadesDurin** [ZhooL/TSX_EnhancedVehicle#46]
I come across Ad Blue on Modhub (https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=129833&title=fs2019)
But it conflict with the Hud icons:
http://prntscr.com/nkm3t9

I use the latest 1.6.3.1 Version of this Mod, maybe you can move the tankhud a bit so that there is no overlay...

**Comment by Bandesss** [comment]
You can edit.
MyGames/Farming Simulator. Modsettings
Themen there Code by Fuel you the right Position to higher.
Edit can the file with Notepad++

Here a Pic 
![1](https://user-images.githubusercontent.com/50829319/58114667-8bdaf800-7bf8-11e9-9b5d-daee3bd6ab05.JPG)

**Comment by cwattyeso** [comment]
I can't even get the DEF Ad Blue Hud Icons to appear in my game if I have the Enhanced Vehicle Mod Installed and Active.
