### ISSUE TITLE
Request: Display Toggle

### ISSUE THREAD

**Issue by Harag9** [ZhooL/TSX_EnhancedVehicle#5]
Just downloaded the mod and used it for about 10 minutes, loving the rpm / temp display as I also use the keyboard steer mod but the display at the top isn't needed all the time and clutters up the screen. Would it be possible to add in a display toggle maybe on the "keypad *" key and move the current keypad * to ctrl+keypad *

but please leave the rmp/temp displays in the dial!

**Comment by ZhooL** [comment]
press "keypad /" to adjust positions if keyboardSteer is in use. you may change all key bindings in the keybindings options menu

**Comment by Harag9** [comment]
The display is above the keyboardsteer - what I mean is a toggle to HIDE the information when not needed... But I've been using it a while now and got use to it being displayed constantly.
