### ISSUE TITLE
Shuttle shift + GPS mod

### ISSUE THREAD

**Issue by Pyrjo** [ZhooL/TSX_EnhancedVehicle#50]
Hi, I have just downloaded and tested this mod, it works fine on my localy hosted server and will soon try upload and run it on my dedicated server.

  But accidently I found a thing right away worth mention. I have the GPS mod installed, and when that mod holds my heading (stearing only) the direction arrows go gray and its no longer functional. No difference from having shuttle shift on or off. Press the breakbutton/pedal makes vehicle go backwards no matter what. But this is just a minor issue, most of the time, you go forward with GPS heading activated, but when break at a standing point makes you go backwards. Thats all.

Thanks for a good mod!

**Comment by Bandesss** [comment]
Das Ding ist tot

**Comment by Pyrjo** [comment]
I found another perfect mod that combines all of this that i was looking for, Transmission. GPS/heading, Lower enginebrake, Adaptive stearing and best of all, AWD control with manual or Tracktion controll of spinning wheels. But maybe this mod will come to top again some day.

**Comment by Bandesss** [comment]
> Ich habe einen anderen perfekten Mod gefunden, der all das kombiniert, wonach ich gesucht habe, Transmission. GPS / Kurs, untere Motorbremse, adaptives Stearing und das Beste von allem, AWD-Steuerung mit manueller oder Tracktion-Steuerung von durchdrehenden Rädern. Aber vielleicht wird dieser Mod eines Tages wieder an die Spitze kommen.

Von welchem Mod redest du ?

**Comment by Pyrjo** [comment]
The one you also interested in i saw. VehicleControlAddon. Das hast alles.
