### ISSUE TITLE
Geht nicht 

### ISSUE THREAD

**Issue by Bandesss** [ZhooL/TSX_EnhancedVehicle#52]
Hallo zusammen, wer auch immer den Mod updatet schaut mal das er wieder mit VCA zusammen geht.
Die letzte Version wo ging mit dem W vorwärts und rückwärts war, 1.6.1.0

Bitte schaut mal danach.
Gruss 
#Modderloben

**Comment by ZhooL** [comment]
Die beiden Mods arbeiten generell nicht gut zusammen, da sie ähnliche Dinge an der Steuerung modifizieren. Achte daher - wie in der Doku beschrieben - drauf, dass nur ein Mod die Kontrolle hat.
