### ISSUE TITLE
Instead of a word in dmg (dutch) it gives a full sentence for the truck

### ISSUE THREAD

**Issue by xCrazyDogx** [ZhooL/TSX_EnhancedVehicle#7]
The screen says it all to be honest when I am in a truck (also visible at the top of the screen), it says with the dmg part (in the red lined box) that a truck can connect to a trailer, all other equipment it says a general name like tractor or trailer or harvester. Not with the truck not sure where it comes from or how to adjust it at this time.
Also not sure if it is cause i use Dutch language (Steam) so didnt try to change steam language and see what it does on english or other languages.

Not a real bug but it looks werid compared to rest that is words.
So wanted to mention it/ show it.

![fsscreen_2019_01_06_20_14_23](https://user-images.githubusercontent.com/22746021/50740544-5d7ff180-11f0-11e9-9c9e-20217bfa8c71.png)

EDIT: it is the truck but couldnt find a way to remove this post :(

**Comment by xCrazyDogx** [comment]
Closing cause i do not think it can be solved since it happens on modded trucks, not on ingame truck or edits from that. So i assume problem lays in the truckmods i noticed it on.

**Comment by ZhooL** [comment]
Unfortunately you're right. I'm just using the "typeDesc" variable and it's set by the vehicle modder.

And I like Dutch :-) I was born near the Netherlands border so I can read and understand most of Dutch.

**Comment by xCrazyDogx** [comment]
do you happen to know where typedesc is set? maybe i can fix it myself in the mod, i am asking at a time im doubting to know for sure where it is
think i found it, testing now, it doesnt use typedesc in the mod but function, change it to typedesc from example that does work

Ok that did the trick, changing from
<typeDesc>$l10n_function_truck</typeDesc>
to
<typeDesc>$l10n_typeDesc_truck</typeDesc> in the mod itself, Thx ZhooL.

**Comment by PitbullSpirit** [comment]
think i found it, testing now, it doesnt use typedesc in the mod but function, change it to typedesc from example that does work
