### ISSUE TITLE
Request: Add Forward/Reverse Direction Key Bindings

### ISSUE THREAD

**Issue by spocane** [ZhooL/TSX_EnhancedVehicle#8]
Love your mod, the replacement to drive control i needed! now with the update of shuttle shift, i am wanting to have Two more keybindings for both Forwards and Reverse (doesn't need to be configured by default). 

It would also be great to have a parking brake feature, I know that you dont really need one, but it adds to the immersion.

Thanks for the effort you are putting into this. I think it is shaping up nicely!

**Comment by vorden44** [comment]
Yes for those of us who use an H-shifter to control forward and reverse, having separate keybindings for each is much appreciated :)

**Comment by ZhooL** [comment]
in version 1.5.1.0

**Comment by spocane** [comment]
Excellently implemented. Thank You for doing so quickly.
