### ISSUE TITLE
Shuttle functions clash with KeyboardSteer

### ISSUE THREAD

**Issue by knuuud** [ZhooL/TSX_EnhancedVehicle#9]
as modders that work the same area does not seem to speak with eachother and make the same functions, these seem to clash up. When your mod goes in to do the same as the shuttle control on Mogli12's KeyboardSteer, these two seem to do  doublecommands. Are you able to make it so your shuttle function are not active if Mogli's are?

**Comment by ZhooL** [comment]
I know it's conflicting. I'll check later if I can do something about this issue.

**Comment by knuuud** [comment]
A check and disable should suffice, but you need to put the check to if his mod has it active. If you only put the check to if his mod is ingame you may loose some users of your shuttle that wants to use both your mods, but your shuttle functions. I guess he should also put a similar check in his mod the other way around to avoid conflict the other way as well.

**Comment by ZhooL** [comment]
As told I've to check. It's easy to detect if another Mod is loaded (g_modIsLoaded.FS19_KeyboardSteer) but it might be not possible to dive deeper into that foreign mod and access its variables to find out if shuttle is enabled there.

**Comment by ZhooL** [comment]
I force deactivation of shuttle function from keyboardSteer if detected. But this will brake the reverse looking cam as well. Can't do more right now.
